apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: fluxy
    spec:
      containers:
      - name: fluxd
        image: weaveworks/fluxd
        imagePullPolicy: Never # must build manually
        args:
        - fluxd
        - --fluxsvc-address=ws://localhost:3030
      - name: fluxsvc
        image: weaveworks/fluxsvc
        imagePullPolicy: Never
        args:
        - fluxsvc
        - --database-source=file://fluxy.db
